project:
  type: website
  output-dir: docs

website:
  title: "Matthew Glasenapp"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
      - cv.qmd
  page-footer:
    center: "&copy; 2024–2026 Matthew Glasenapp"

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: false
    link-external-newwindow: true

editor: visual
