project:
  type: website
  output-dir: docs

website:
  title: "Matthew Glasenapp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
      - tutorials.qmd
      - cv.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

